services:
  postgres:
    container_name: spotify-db
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: whatever
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
